# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: check
  check:
    deps:
      - task: lint
    cmds:
      - renovate-config-validator --strict --no-global default.json self.json .github/renovate.json
      - deno test --allow-read
  fmt:
    cmds:
      - dprint fmt
  lint:
    cmds:
      - dprint check
      - deno lint
      - typos . .github .vscode
