# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: check
  check:
    deps:
      - task: lint
    cmds:
      - renovate-config-validator default.json self.json
      - deno test --allow-read
  fmt:
    cmds:
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    cmds:
      - dprint check
      - deno lint
      - typos . .github .vscode
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - nixfmt --version
      - renovate --version
      - deno --version
