# https://taskfile.dev

version: '3'
tasks:
  default:
    deps:
      - task: fmt
      - task: lint
  check:
    deps:
      - task: lint
  fmt:
    cmds:
      - dprint fmt
      - yamlfmt -formatter retain_line_breaks=true .
      - nixpkgs-fmt ./*.nix
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
