# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: check
  check:
    deps:
      - task: lint
    cmds:
      - renovate-config-validator --strict --no-global default.json .github/renovate.json
      - npm test
  fmt:
    cmds:
      - dprint fmt
  lint:
    cmds:
      - dprint check
      - oxlint -c .oxlintrc.json --deny-warnings
      - typos . .github .vscode
