name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'
jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          # Keep same version as used in *.nix
          dprint-version: '0.40.0'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.20.9
        with:
          files: |
            .
            .github
            .vscode
