name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'
jobs:
  dprint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      # Syntax https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for 'n.0'
        dprint-version: [
          '', # empty means to latest: https://github.com/dprint/check/blob/2f1cf31537886c3bfb05591c031f7744e48ba8a1/action.yml#L8
          '0.49.1', # selfup {"extract":"\\d[^']+","replacer":["dprint", "--version"], "nth": 2}
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@2f1cf31537886c3bfb05591c031f7744e48ba8a1 # v2.2
        with:
          dprint-version: '${{ matrix.dprint-version }}'
      - name: Make sure dprint status
        run: |
          dprint --version
          dprint output-file-paths
          dprint output-resolved-config

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: 'crate-ci/typos@v1.27.3' # selfup {"extract":"\\d[^']+","replacer":["typos", "--version"], "nth": 2}
        with:
          files: |
            .
            .github
            .vscode
